version: '3'
services:
  rdcaches:
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"

  roach1:
    image: cockroachdb/cockroach
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data

  roach2:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach1
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data
    links:
      - roach1
  
  bgin:
    image: bgin
    ports:
      - "6968:5000"
    environment:
      - GIN_MODE=release
      - APP_PORT=5000
      - APP_HOST=0.0.0.0
      - DB_HOST=roach1
      - DB_PORT=26257
      - DB_NAME=bgin
      - DB_USER=root
      - DB_PASSWORD=
      - ACL_ADDR=172.19.0.0/24
      - REDIS_HOST=rdcaches
      - REDIS_PORT=6379
    command: ./main -e production
    links:
      - roach1
      - rdcaches